Repository stolostron/multicloud-operators-subscription-release, pull requests merged in 2019-11, with the labels that each got.

#17 Move to klog
  cmd/manager/main.go
  go.mod
  go.sum
  pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_suite_test.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_suite_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_suite_test.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/L

#18 Implement labelSelector
  deploy/crds/app_v1alpha1_helmchartsubscription_crd.yaml
  pkg/apis/app/v1alpha1/helmchartsubscription_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
  pkg/utils/kubernetes.go
  pkg/utils/kubernetes_test.go
Labels: approved, lgtm, size/L

#19 Dvernier release name too short 740
  docs/deployment.md
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
Labels: approved, lgtm, size/M

#20 Reduce nb reconcile, add uni-tests
  pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
Labels: approved, lgtm, size/L

#21 Migrate to 0.12.0
  cmd/manager/main.go
  deploy/crds/app.ibm.com_helmchartsubscriptions_crd.yaml
  deploy/crds/app.ibm.com_helmreleases_crd.yaml
  deploy/crds/app_v1alpha1_helmchartsubscription_crd.yaml
  deploy/crds/app_v1alpha1_helmrelease_crd.yaml
  go.mod
  go.sum
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/helmchartsubscription/helmchartsubscription_controller_suite_test.go
  pkg/controller/helmchartsubscription/helmchartsubscription_controller_test.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_suite_test.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber_suite_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils_suite_test.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/XXL

#23 Klog.InitFlags misplaced
  cmd/manager/main.go
Labels: approved, lgtm, size/XS

#24 Dvernier password access token
  Makefile
  common/scripts/.githooks/pre-commit
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/utils/helmrepoutils.go
  pkg/utils/kubernetes.go
  pkg/utils/kubernetes_test.go
Labels: approved, lgtm, size/M

#25 Add finalizer and manage delete
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/utils/helmrelease.go
  pkg/utils/helmrelease_test.go
Labels: approved, lgtm, size/L

#26 Code cleaning and refactoring
  docs/deployment.md
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/XXL

#27 Check if helmrelease installed before uninstall
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/utils/helmrelease.go
Labels: approved, lgtm, size/S

#28 Don't read value on delete
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/helmreleasemgr/helmreleasemgr.go
Labels: approved, lgtm, size/L

#29 Create fake chart.yaml on del if download failed
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/L

#30 Add logs to find out why test fails on prow
  deploy/crds/app.ibm.com_helmchartsubscriptions_crd.yaml
  deploy/crds/app.ibm.com_helmreleases_crd.yaml
  pkg/apis/app/v1alpha1/helmchartsubscription_types.go
  pkg/apis/app/v1alpha1/helmrelease_types.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
Labels: approved, lgtm, size/M

#31 Add support for file scheme url on helmrepo
  deploy/operator.yaml
  docs/deployment.md
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/L

#33 Add creation secret with releaseName
  docs/deployment.md
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/controller/helmrelease/helmreleasemgr.go
  pkg/helmreleasemgr/helmreleasemgr_suite_test.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/XL

#34 Dvernier secret releasename
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/controller/helmrelease/helmreleasemgr.go
Labels: approved, lgtm, size/S

#35 Manage release name change
  cmd/manager/main.go
  pkg/apis/app/v1alpha1/helmrelease_types.go
  pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/controller/helmrelease/helmreleasemgr.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/utils/helmrepoutils.go
  pkg/utils/kubernetes.go
Labels: approved, lgtm, size/L

#37 add team members to owner list and several other updates/fixes
  OWNERS
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/controller/helmrelease/helmreleasemgr.go
Labels: approved, lgtm, size/L
