Repository stolostron/multicloud-operators-subscription-release, pull requests merged in 2019-10, with the labels that each got.

#3 Initial load on github.com
  .gitignore
  .travis.yml
  Configfile
  Makefile
  OWNERS
  README.md
  build/Dockerfile
  build/bin/entrypoint
  build/bin/user_setup
  build/install-operator-sdk.sh
  cmd/manager/main.go
  deploy/crds/app_v1alpha1_helmchartsubscription_cr.yaml
  deploy/crds/app_v1alpha1_helmchartsubscription_crd.yaml
  deploy/crds/app_v1alpha1_helmrelease_cr.yaml
  deploy/crds/app_v1alpha1_helmrelease_crd.yaml
  deploy/operator.yaml
  deploy/role.yaml
  deploy/role_binding.yaml
  deploy/service_account.yaml
  go.mod
  go.sum
  pkg/apis/addtoscheme_app_v1alpha1.go
  pkg/apis/apis.go
  pkg/apis/app/group.go
  pkg/apis/app/v1alpha1/doc.go
  pkg/apis/app/v1alpha1/helmchartsubscription_types.go
  pkg/apis/app/v1alpha1/helmrelease_types.go
  pkg/apis/app/v1alpha1/register.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/add_helmchartsubscription.go
  pkg/controller/add_helmrelease.go
  pkg/controller/controller.go
  pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/helmreleasemgr/subscriptionrelease_test.go
  pkg/helmreleasemgr/subscriptionreleasemgr.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  tools.go
  travis-env.sh
  version/version.go
Labels: approved, lgtm, size/XXL

#4 Update travis and makefile
  .travis.yml
  Makefile
Labels: approved, size/M

#6 Typo fixed on lines 03 & 09 & 81
  README.md
Labels: approved, lgtm, size/XS

#5 Make the IMAGE_NAME a parameter
  Configfile
  Makefile
Labels: approved, lgtm, size/S

#8 Dvernier signoff
  .travis.yml
  CONTRIBUTING.md
  Configfile
  Makefile
  README.md
  RELEASE.md
  build/Dockerfile
  build/install-operator-sdk.sh
  cmd/manager/main.go
  common/Makefile.common.mk
  common/config/.golangci.yml
  common/config/.hadolint.yml
  common/config/.yamllint.yml
  common/config/mdl.rb
  common/config/sass-lint.yml
  common/config/tslint.json
  common/scripts/codecov.sh
  common/scripts/config_docker.sh
  common/scripts/gobuild.sh
  common/scripts/lint_copyright_banner.sh
  common/scripts/lint_go.sh
  deploy/crds/app_v1alpha1_helmchartsubscription_crd.yaml
  deploy/crds/app_v1alpha1_helmrelease_cr.yaml
  deploy/operator.yaml
  deploy/role.yaml
  docs/development.md
  go.mod
  go.sum
  hack/boilerplate.go.txt
  pkg/apis/app/v1alpha1/helmchartsubscription_types.go
  pkg/apis/app/v1alpha1/helmrelease_types.go
  pkg/apis/app/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/controller.go
  pkg/controller/helmchartsubscription/helmchartsubscription_controller.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_suite_test.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/helmreleasemgr/helmreleasemgr.go
  pkg/helmreleasemgr/subscriptionrelease_test.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  tools.go
  travis-env.sh
Labels: approved, lgtm, size/XXL

#9 install operator-sdk
  Makefile
  build/install-operator-sdk.sh
Labels: approved, lgtm, size/M

#11 ignore dco check for organization members
  .github/dco.yml
Labels: approved, lgtm, size/XS

#12 Add helmcharts examples
  .gitignore
  Makefile
  build/generate-helmrepo.sh
  common/Makefile.common.mk
  test/github/subscription-release-test-1/.helmignore
  test/github/subscription-release-test-1/Chart.yaml
  test/github/subscription-release-test-1/templates/_helpers.tpl
  test/github/subscription-release-test-1/templates/deployment_subscription_release.yaml
  test/github/subscription-release-test-1/values.yaml
  test/github/subscription-release-test-2/.helmignore
  test/github/subscription-release-test-2/Chart.yaml
  test/github/subscription-release-test-2/templates/_helpers.tpl
  test/github/subscription-release-test-2/templates/deployment_subscription_release.yaml
  test/github/subscription-release-test-2/values.yaml
  test/helmrepo/index.yaml
  test/helmrepo/subscription-release-test-1-0.1.0.tgz
  test/helmrepo/subscription-release-test-1-0.2.0.tgz
  test/helmrepo/subscription-release-test-2-0.1.0.tgz
Labels: approved, lgtm, size/XL

#13 Add Unit Tests
  Makefile
  README.md
  build/generate-helmrepo.sh
  go.sum
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
  test/helmrepo/index.yaml
  test/helmrepo/subscription-release-test-1-0.1.0.tgz
  test/helmrepo/subscription-release-test-1-0.2.0.tgz
  test/helmrepo/subscription-release-test-2-0.1.0.tgz
Labels: approved, lgtm, size/L

#15 Badge fix
  README.md
Labels: approved, lgtm, size/XS

#16 Add unit-test on subscriber, helmrleeasemgr...
  go.sum
  pkg/helmreleasemgr/helmreleasemgr_suite_test.go
  pkg/helmreleasemgr/helmreleasemgr_test.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_suite_test.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils_suite_test.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/XL
