Repository stolostron/multicloud-operators-subscription-release, pull requests merged in 2020-01, with the labels that each got.

#38 fix helm repo utils download chart from helm repo not handling errors properly
  OWNERS
  deploy/crds/app_v1alpha1_helmchartsubscription_cr.yaml
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/L

#41 update owners of the repo
  OWNERS
Labels: approved, lgtm, size/XS

#40 Fix image reference by pointing to quay.io
  deploy/operator.yaml
Labels: approved, lgtm, needs-ok-to-test, size/XS

#42 consolidate releasename and cr name into just using cr name
  deploy/crds/app.ibm.com_helmreleases_crd.yaml
  docs/deployment.md
  pkg/apis/app/v1alpha1/helmrelease_types.go
  pkg/apis/app/v1alpha1/zz_generated.openapi.go
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmrelease_controller_test.go
  pkg/controller/helmrelease/helmreleasemgr.go
  pkg/helmreposubscriber/hrsubscriber.go
  pkg/helmreposubscriber/hrsubscriber_test.go
  pkg/utils/helmrepoutils.go
  pkg/utils/helmrepoutils_test.go
Labels: approved, lgtm, size/L
