Repository stolostron/multicloud-operators-subscription-release, pull requests merged in 2022-05, with the labels that each got.

#223 trigger image build
  README.md
Labels: approved, dco-signoff: no

#225 toggle cicd build
  README.md
Labels: approved, dco-signoff: yes

#226 set default value for helmrelease chart directory
  pkg/controller/helmrelease/helmrelease_controller.go
  pkg/controller/helmrelease/helmreleasemgr.go
Labels: approved, lgtm, dco-signoff: yes
